# Masdif configuration
# This file contains most configuration options for Masdif. You can configure also RAILS_ENV specific settings, if
# you need different configuration for different environments. ERB is also supported.
#
# Please note: environment variables are already set via the .env file prior before configuration of Masdif,
# so you can use them here as well.

shared:
  admin_interface:
    enabled: <%= ENV['ADMIN_INTERFACE_ENABLED'] || false %>
    # The path to where the admin interface is served is configurable via config/initializers/active_admin.rb
    # The default path is /admin.

  # Sdifi chat widget configuration options
  chat_widget:
    # Enable or disable the chat widget
    enabled: true
    # The path to where the chat widget is served
    path: /

  # Feedback configuration options
  feedback:
    # Forward the feedback to dialog system or not. In case of false, the feedback is only stored in the database
    forward: false
    # The intent to where the feedback is served
    intent: feedback
    # include reply message for which the feedback is given
    include_reply_text: true

  languages:
    supported:
      - lang: is-IS
        explanation: Ég tala íslensku
    # default language of the chatbot, i.e. the language of the model, the knowledge base, etc.
    # This needs to be one of the supported languages above
    default: is-IS

  motd:
    # Rasa intent to use for the message of the day
    rasa_intent: motd
    # Alternative text to use if the rasa intent is not defined, language specific
    default:
      is-IS:
        - "Halló"
        - "Hvernig get ég aðstoðað?"

  # Text to speech
  tts:
    # Enable or disable the text to speech feature
    enabled: true
    # The TTS language
    language: is-IS
    # timeout in seconds for attachment cleanup
    attachment_timeout: <%= ENV['TTS_ATTACHMENT_TIMEOUT'] || 14.days %>
    # The type of TTS service to use, currently supported: "SIM"
    type: SIM
    # Settings for SIM TTS service
    # The voice to use for the text to speech feature
    default_voice: <%= ENV['TTS_VOICE_ID'] || "Alfur" %>
    host: <%= ENV['TTS_HOST'] %>
    base_path: <%= ENV['TTS_BASE_PATH'] %>
    host_scheme: <%= ENV['TTS_HOST_SCHEME'] %>
    # debugs tts requests
    debugging: false


test:
  languages:
    supported:
      - lang: is-IS
        explanation: Ég tala íslensku
      - lang: en-US
        explanation: I speak English
    default: is-IS

  motd:
    rasa_intent: motd
    default:
      is-IS:
        - "Halló"
        - "Hvernig get ég aðstoðað?"
      en-US:
        - "Hello"
        - "How can I help you?"
