name: Masdif Build containers
run-name: ${{ github.actor }} builds Masdif for ${{ github.ref }} on ${{ github.event_name }}
env:
  APPLICATION_VERSION: ${{ github.sha }}
  FUSEKI_VERSION: 4.7.0
  POSTGRES_HOSTNAME: db
  POSTGRES_USER: postgres
  RABBITMQ_USER: user
  RAILS_SERVE_STATIC_FILES: true
  RAILS_LOG_TO_STDOUT: true
  RASA_REPO_DIR: ./rasa
  RASA_VERSION: 3.4.9
  REGISTRY_URL: ${{ vars.REGISTRY_URL }}

# Only run if no tag is pushed
on:
  push:
    branches:
      - '**'
jobs:
  docker-build-municipality:
    runs-on: ubuntu-latest
    environment: Action Build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout municipality repository
        uses: actions/checkout@v3
        with:
          repository: SDiFI/sdifi_rasa_akranes
          path: ${{ env.RASA_REPO_DIR }}
      - name: Build masdif images
        env:
          RAILS_CREDENTIALS: ${{ secrets.RAILS_CREDENTIALS }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          ci/create_credentials.sh $RAILS_CREDENTIALS $RAILS_MASTER_KEY
          cp .env.example .env
          cat docker-compose.yml $RASA_REPO_DIR/masdif_override_template.yml | docker-compose -f - build
